package pageFactory
	
import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._
//import akka.util.duration._
import pageHeaders._


object checkoutPF{

	val plp_Checkout = exec(http("Checkout_popUp")
			.get("/yacceleratorstorefront/electronics/en/cart/checkout")
			.headers(headers.headers_0)
			.check(regex("""<input type="hidden" name="CSRFToken" value="([^"]*)" />""").saveAs("requestVerificationToken"))
			 ).pause(17)
	
	val checkout = exec(http("checkout")
			.get("/yacceleratorstorefront/electronics/en/cart/checkout")
			.headers(headers.headers_0)
			.check(regex("""<input type="hidden" name="CSRFToken" value="([^"]*)" />""").saveAs("requestVerificationToken"))).pause(31)
	
	
	val logininterceptor_login = exec(http("logininterceptor_login")
			.post("/yacceleratorstorefront/electronics/en/checkout/j_spring_security_check")
			.headers(headers.headers_0)
			.formParam("j_username", "may16_1@gmail.com")
			.formParam("j_password", "123456")
			.formParam("CSRFToken", "${requestVerificationToken}"))
	
	//Shipping,Billing And PaymentPage
	val shippingCountry = exec(http("shippingCountry")
			.get("/yacceleratorstorefront/electronics/en/my-account/addressform?addressCode=&countryIsoCode=US")
			.headers(headers.headers_9)
			.check(regex("""<input type="hidden" name="CSRFToken" value="([^"]*)" />""").saveAs("requestVerificationToken")))
		.pause(28)
	val shippingAddress = exec(http("shippingAddress")
			.post("/yacceleratorstorefront/electronics/en/checkout/multi/delivery-address/add")
			.headers(headers.headers_0)
			.formParam("addressId", "")
			.formParam("bill_state", "")
			.formParam("countryIso", "US")
			.formParam("titleCode", "mrs")
			.formParam("firstName", "demo")
			.formParam("lastName", "testing")
			.formParam("line1", "795 E DRAGRAM")
			.formParam("line2", "")
			.formParam("townCity", "TUCSON")
			.formParam("regionIso", "US-AZ")
			.formParam("postcode", "85705")
			.formParam("phone", "")
			.formParam("CSRFToken", "${requestVerificationToken}")
			//.formParam("CSRFToken", "c9cbac01-e526-4377-836a-e8af4b9c56b3")
			.formParam("_saveInAddressBook", "on")
		    .formParam("CSRFToken", "${requestVerificationToken}"))
			//.formParam("CSRFToken", "c9cbac01-e526-4377-836a-e8af4b9c56b3"))
		.pause(7)
	val deliveryMethod = exec(http("deliveryMethod")
			.get("/yacceleratorstorefront/electronics/en/checkout/multi/delivery-method/select?delivery_method=standard-gross")
			.headers(headers.headers_0))
		.pause(2)
	val billingCheckbox = exec(http("billingCheckbox")
			.get("/yacceleratorstorefront/electronics/en/checkout/multi/sop/billingaddressform?countryIsoCode=US&useDeliveryAddress=true")
			.headers(headers.headers_9))
		.pause(36)
	val paymentDetails = exec(http("paymentDetails")
			.post("/acceleratorservices/sop-mock/process")
			.headers(headers.headers_0)
			.formParam("orderPage_receiptResponseURL", "https://b2caccelerator.pragiti.com/yacceleratorstorefront/electronics/en/checkout/multi/sop/response")
			.formParam("orderPage_declineResponseURL", "https://b2caccelerator.pragiti.com/yacceleratorstorefront/electronics/en/checkout/multi/sop/response")
			.formParam("orderPage_cancelResponseURL", "https://b2caccelerator.pragiti.com/yacceleratorstorefront/electronics/en/checkout/multi/sop/response")
			.formParam("orderPage_version", "7")
			.formParam("amount", "0")
			.formParam("orderPage_timestamp", "1558876584225")
			.formParam("orderPage_transactionType", "subscription")
			.formParam("merchantID", "your_merchant_id")
			.formParam("orderPage_signaturePublic", "NAB7r5xeAgDYpk16HMqVtyiOmYY=")
			.formParam("currency", "USD")
			.formParam("orderPage_serialNumber", "your_serial_number")
			.formParam("recurringSubscriptionInfo_signaturePublic", "omxZoMM1Cve51sIZtp3crlUrxAI=")
			.formParam("recurringSubscriptionInfo_automaticRenew", "false")
			.formParam("recurringSubscriptionInfo_amount", "0")
			.formParam("recurringSubscriptionInfo_startDate", "20190526")
			.formParam("recurringSubscriptionInfo_numberOfPayments", "0")
			.formParam("recurringSubscriptionInfo_frequency", "on-demand")
			.formParam("billTo_email", "may16_1@gmail.com")
			.formParam("card_cardType", "001")
			.formParam("card_nameOnCard", "VISA")
			.formParam("card_accountNumber", "4111111111111111")
			.formParam("card_expirationMonth", "12")
			.formParam("card_expirationYear", "2027")
			.formParam("card_cvNumber", "123")
			.formParam("card_issueNumber", "")
			.formParam("_savePaymentInfo", "on")
			.formParam("useDeliveryAddress", "true")
			.formParam("_useDeliveryAddress", "on")
			.formParam("billTo_email", "may16_1@gmail.com")
			.formParam("billTo_email", "may16_1@gmail.com")
			.formParam("billTo_country", "US")
			.formParam("billTo_titleCode", "mrs")
			.formParam("billTo_firstName", "demo")
			.formParam("billTo_lastName", "testing")
			.formParam("billTo_street1", "795 E DRAGRAM")
			.formParam("billTo_street2", "")
			.formParam("billTo_city", "TUCSON")
			.formParam("billTo_state", "AZ")
			.formParam("billTo_postalCode", "85705")
			.formParam("billTo_phoneNumber", "")
			.formParam("CSRFToken", "${requestVerificationToken}")
			.formParam("CSRFToken", "${requestVerificationToken}"))
			//.formParam("CSRFToken", "c9cbac01-e526-4377-836a-e8af4b9c56b3")
			//.formParam("CSRFToken", "c9cbac01-e526-4377-836a-e8af4b9c56b3")
		/*	
			.resources(http("paymentMerchantResponse")
			.post("/yacceleratorstorefront/electronics/en/checkout/multi/sop/response")
			.headers(headers_0)
			.formParam("billTo_city", "TUCSON")
			.formParam("billTo_email", "may16_1@gmail.com")
			.formParam("recurringSubscriptionInfo_automaticRenew", "false")
			.formParam("decision_publicSignature", "mEhlMRLCsuPimhp50ElrY94zFyc=")
			.formParam("billTo_titleCode", "mrs")
			.formParam("CSRFToken", "c9cbac01-e526-4377-836a-e8af4b9c56b3")
			.formParam("billTo_country", "US")
			.formParam("billTo_lastName", "testing")
			.formParam("billTo_street2", "")
			.formParam("ccAuthReply_cvCode", "M")
			.formParam("billTo_street1", "795 E DRAGRAM")
			.formParam("orderPage_declineResponseURL", "https://b2caccelerator.pragiti.com/yacceleratorstorefront/electronics/en/checkout/multi/sop/response")
			.formParam("orderPage_transactionType", "subscription")
			.formParam("_savePaymentInfo", "on")
			.formParam("card_cardType", "001")
			.formParam("recurringSubscriptionInfo_startDate", "20190526")
			.formParam("useDeliveryAddress", "true")
			.formParam("recurringSubscriptionInfo_frequency", "on-demand")
			.formParam("orderPage_signaturePublic", "NAB7r5xeAgDYpk16HMqVtyiOmYY=")
			.formParam("currency", "USD")
			.formParam("reasonCode", "100")
			.formParam("card_accountNumber", "************1111")
			.formParam("orderPage_serialNumber", "your_serial_number")
			.formParam("recurringSubscriptionInfo_signaturePublic", "omxZoMM1Cve51sIZtp3crlUrxAI=")
			.formParam("paySubscriptionCreateReply_subscriptionID", "c2fb30ec-0835-482e-b98f-7278e3a38038")
			.formParam("amount", "0")
			.formParam("card_issueNumber", "")
			.formParam("decision", "ACCEPT")
			.formParam("recurringSubscriptionInfo_numberOfPayments", "0")
			.formParam("card_nameOnCard", "VISA")
			.formParam("orderPage_receiptResponseURL", "https://b2caccelerator.pragiti.com/yacceleratorstorefront/electronics/en/checkout/multi/sop/response")
			.formParam("billTo_postalCode", "85705")
			.formParam("orderPage_version", "7")
			.formParam("orderPage_timestamp", "1558876584225")
			.formParam("_useDeliveryAddress", "on")
			.formParam("billTo_firstName", "demo")
			.formParam("billTo_state", "AZ")
			.formParam("card_expirationMonth", "12")
			.formParam("recurringSubscriptionInfo_amount", "0")
			.formParam("merchantID", "your_merchant_id")
			.formParam("orderPage_cancelResponseURL", "https://b2caccelerator.pragiti.com/yacceleratorstorefront/electronics/en/checkout/multi/sop/response")
			.formParam("card_expirationYear", "2027")
			.formParam("billTo_phoneNumber", "")
			.formParam("paySubscriptionCreateReply_subscriptionIDPublicSignature", "fhLb1JCenwlrzyAGqqly8nGFyqQ=")))*/
		.pause(5)
	
		val orderSummary = exec(http("orderSummary")
			.post("/yacceleratorstorefront/electronics/en/checkout/multi/summary/view")
			.headers(headers.headers_0))
		val placeOrder = exec(http("placeOrder")
			.post("/yacceleratorstorefront/electronics/en/checkout/multi/summary/placeOrder")
			.headers(headers.headers_0)
			.formParam("termsCheck", "true")
			.formParam("_termsCheck", "on")			  
			.formParam("CSRFToken", "${requestVerificationToken}"))
			//.formParam("CSRFToken", "c9cbac01-e526-4377-836a-e8af4b9c56b3"))
}
