package computerdatabase

import scala.concurrent.duration._

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._

class OrderPlaced_B1 extends Simulation {


  val httpProtocol = http
    .baseUrl("https://192.168.4.76:9002")
    .inferHtmlResources()
    .acceptHeader("text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8")
    .acceptEncodingHeader("gzip, deflate")
    .acceptLanguageHeader("en-US,en;q=0.5")
    .userAgentHeader("Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0")

  val headers_0 = Map(
    "Cache-Control" -> "no-cache",
    "Pragma" -> "no-cache",
    "Upgrade-Insecure-Requests" -> "1")

  val headers_6 = Map(
    "Accept" -> "text/html, */*; q=0.01",
    "Cache-Control" -> "no-cache",
    "Pragma" -> "no-cache",
    "X-Requested-With" -> "XMLHttpRequest")

  val uri1 = "https://192.168.4.76:9002/yacceleratorstorefront"
  val uri2 = "https://electronics.local:9002"

  val scn = scenario("RegCheckoutB1")
    .exec(http("request_0")
      .get("/yacceleratorstorefront/?site=electronics")
      .headers(headers_0))
    .pause(7)
    .exec(http("request_1")
      .get("/yacceleratorstorefront/electronics/en/login")
      .headers(headers_0)
      .check(regex("""<input type="hidden" name="CSRFToken" value="([^"]*)" />""")
        .saveAs("requestVerificationToken"))
    )
    .pause(51)
    .exec(http("request_2")
      .post("/yacceleratorstorefront/electronics/en/login/register")
      .headers(headers_0)
      .formParam("titleCode", "mr")
      .formParam("firstName", "testing1")
      .formParam("lastName", "testing1")
      .formParam("email", "testb3@gmail.com")
      .formParam("pwd", "123456")
      .formParam("checkPwd", "123456")
      .formParam("consentForm.consentTemplateId", "MARKETING_NEWSLETTER")
      .formParam("consentForm.consentTemplateVersion", "0")
      .formParam("termsCheck", "true")
      .formParam("CSRFToken", "${requestVerificationToken}"))
    .pause(19)
    .exec(http("request_3")
      .get("/yacceleratorstorefront/electronics/en/Brands/c/brands")
      .headers(headers_0))
    .pause(9)
    .exec(http("request_4")
      .get("/yacceleratorstorefront/electronics/en/cart")
      .headers(headers_0))
    .pause(10)
    .exec(http("request_5")
      .get("/yacceleratorstorefront/electronics/en/cart/checkout")
      .headers(headers_0))
    .pause(14)
    .exec(http("request_6")
      .get("/yacceleratorstorefront/electronics/en/my-account/addressform?addressCode=&countryIsoCode=US")
      .headers(headers_6)
      .check(regex("""<input type="hidden" name="CSRFToken" value="([^"]*)" />""")
        .saveAs("requestVerificationToken"))
    )
    .pause(27)
    .exec(http("request_7")
      .post("/yacceleratorstorefront/electronics/en/checkout/multi/delivery-address/add")
      .headers(headers_0)
      .formParam("addressId", "")
      .formParam("bill_state", "")
      .formParam("countryIso", "US")
      .formParam("titleCode", "mr")
      .formParam("firstName", "test")
      .formParam("lastName", "test")
      .formParam("line1", "795 E DRAGRAM")
      .formParam("line2", "")
      .formParam("townCity", "TUCSON")
      .formParam("regionIso", "US-AZ")
      .formParam("postcode", "85705")
      .formParam("phone", "")
      .formParam("CSRFToken", "${requestVerificationToken}")
      .formParam("_saveInAddressBook", "on")
      .formParam("CSRFToken", "${requestVerificationToken}"))
    .pause(6)
    .exec(http("request_8")
      .get("/yacceleratorstorefront/electronics/en/checkout/multi/delivery-method/select?delivery_method=premium-gross")
      .headers(headers_0)
      .check(regex("""<input type="hidden" name="CSRFToken" value="([^"]*)" />""")
        .saveAs("requestVerificationToken"))
    )
    .pause(1)
    .exec(http("request_9")
      .get("/yacceleratorstorefront/electronics/en/checkout/multi/sop/billingaddressform?countryIsoCode=US&useDeliveryAddress=true")
      .headers(headers_6)
      )
    .pause(19)
    .exec(http("request_10")
      .post(uri2 + "/acceleratorservices/sop-mock/process")
      .headers(headers_0)
      .formParam("orderPage_receiptResponseURL", "https://electronics.local:9002/yacceleratorstorefront/electronics/en/checkout/multi/sop/response")
      .formParam("orderPage_declineResponseURL", "https://electronics.local:9002/yacceleratorstorefront/electronics/en/checkout/multi/sop/response")
      .formParam("orderPage_cancelResponseURL", "https://electronics.local:9002/yacceleratorstorefront/electronics/en/checkout/multi/sop/response")
      .formParam("orderPage_version", "7")
      .formParam("amount", "0")
      .formParam("orderPage_timestamp", "1556099801533")
      .formParam("orderPage_transactionType", "subscription")
      .formParam("merchantID", "your_merchant_id")
      .formParam("orderPage_signaturePublic", "B jFGdUme4fUOPJ0hcZwePmppUM=")
      .formParam("currency", "USD")
      .formParam("orderPage_serialNumber", "your_serial_number")
      .formParam("recurringSubscriptionInfo_signaturePublic", "lqQYBoxLhBkx/0JUKb/gApfxcGU=")
      .formParam("recurringSubscriptionInfo_automaticRenew", "false")
      .formParam("recurringSubscriptionInfo_amount", "0")
      .formParam("recurringSubscriptionInfo_startDate", "20190424")
      .formParam("recurringSubscriptionInfo_numberOfPayments", "0")
      .formParam("recurringSubscriptionInfo_frequency", "on-demand")
      .formParam("billTo_email", "testb1@gmail.com")
      .formParam("card_cardType", "001")
      .formParam("card_nameOnCard", "")
      .formParam("card_accountNumber", "4111111111111111")
      .formParam("card_expirationMonth", "6")
      .formParam("card_expirationYear", "2024")
      .formParam("card_cvNumber", "123")
      .formParam("card_issueNumber", "")
      .formParam("_savePaymentInfo", "on")
      .formParam("useDeliveryAddress", "true")
      .formParam("_useDeliveryAddress", "on")
      .formParam("billTo_email", "testb1@gmail.com")
      .formParam("billTo_email", "testb1@gmail.com")
      .formParam("billTo_country", "US")
      .formParam("billTo_titleCode", "mr")
      .formParam("billTo_firstName", "test")
      .formParam("billTo_lastName", "test")
      .formParam("billTo_street1", "795 E DRAGRAM")
      .formParam("billTo_street2", "")
      .formParam("billTo_city", "TUCSON")
      .formParam("billTo_state", "AZ")
      .formParam("billTo_postalCode", "85705")
      .formParam("billTo_phoneNumber", "")
      .formParam("CSRFToken", "${requestVerificationToken}")
      .formParam("CSRFToken", "${requestVerificationToken}"))
  /*		.resources(http("request_11")
      .post(uri2 + "/yacceleratorstorefront/electronics/en/checkout/multi/sop/response")
      .headers(headers_0)
      .formParam("billTo_city", "TUCSON")
      .formParam("billTo_email", "testb1@gmail.com")
      .formParam("recurringSubscriptionInfo_automaticRenew", "false")
      .formParam("decision_publicSignature", "mEhlMRLCsuPimhp50ElrY94zFyc=")
      .formParam("billTo_titleCode", "mr")
      .formParam("CSRFToken", "4fbf32d7-e962-49dc-bc2f-9d7f1e828af0")
      .formParam("billTo_country", "US")
      .formParam("billTo_lastName", "test")
      .formParam("billTo_street2", "")
      .formParam("ccAuthReply_cvCode", "M")
      .formParam("billTo_street1", "795 E DRAGRAM")
      .formParam("orderPage_declineResponseURL", "https://electronics.local:9002/yacceleratorstorefront/electronics/en/checkout/multi/sop/response")
      .formParam("orderPage_transactionType", "subscription")
      .formParam("_savePaymentInfo", "on")
      .formParam("card_cardType", "001")
      .formParam("recurringSubscriptionInfo_startDate", "20190424")
      .formParam("useDeliveryAddress", "true")
      .formParam("recurringSubscriptionInfo_frequency", "on-demand")
      .formParam("orderPage_signaturePublic", "B jFGdUme4fUOPJ0hcZwePmppUM=")
      .formParam("currency", "USD")
      .formParam("reasonCode", "100")
      .formParam("card_accountNumber", "************1111")
      .formParam("orderPage_serialNumber", "your_serial_number")
      .formParam("recurringSubscriptionInfo_signaturePublic", "lqQYBoxLhBkx/0JUKb/gApfxcGU=")
      .formParam("paySubscriptionCreateReply_subscriptionID", "19b726d0-0e34-4662-99f1-adc38cafb52b")
      .formParam("amount", "0")
      .formParam("card_issueNumber", "")
      .formParam("decision", "ACCEPT")
      .formParam("recurringSubscriptionInfo_numberOfPayments", "0")
      .formParam("card_nameOnCard", "")
      .formParam("orderPage_receiptResponseURL", "https://electronics.local:9002/yacceleratorstorefront/electronics/en/checkout/multi/sop/response")
      .formParam("billTo_postalCode", "85705")
      .formParam("orderPage_version", "7")
      .formParam("orderPage_timestamp", "1556099801533")
      .formParam("_useDeliveryAddress", "on")
      .formParam("billTo_firstName", "test")
      .formParam("billTo_state", "AZ")
      .formParam("card_expirationMonth", "6")
      .formParam("recurringSubscriptionInfo_amount", "0")
      .formParam("merchantID", "your_merchant_id")
      .formParam("orderPage_cancelResponseURL", "https://electronics.local:9002/yacceleratorstorefront/electronics/en/checkout/multi/sop/response")
      .formParam("card_expirationYear", "2024")
      .formParam("billTo_phoneNumber", "")
      .formParam("paySubscriptionCreateReply_subscriptionIDPublicSignature", "JCxeJAx5EcYY13f5jIiI/iZYgpU=")))*/

  setUp(scn.inject(atOnceUsers(1))).protocols(httpProtocol)
}